name: PHPVM Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install BATS (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local

      - name: Install BATS (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install bats-core

      - name: Run BATS tests
        run: |
          bats phpvm.bats
