name: PHPVM Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Set up permissions for the script
      - name: Make script executable
        run: chmod +x ./phpvm.sh

      # Run the integrated self-tests
      - name: Run integrated tests
        run: ./phpvm.sh test
